rvm:
  - 1.9.3
  - ruby-head
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-19mode
# HACK: Fix problems with native libraries on ruby-head
before_install:
  - gem install nokogiri redcarpet rugged -- --with-cflags='--std=gnu99'
